### ISSUE TITLE
No reward record created for iteration.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#11]
3/2/22 freeosgov ver 0.9.4 account: vivvestin
1. Ran SVR activities and Claim for vivvestin in iter 3387. No reward record created for new iteration 3387. Only 3 reward records shown for 3382, 3383, 3384.

![Account - Proton Testnet 03-02-2022 15-32-42](https://user-images.githubusercontent.com/77765830/152272150-b38073db-fe66-4240-aff7-d6e5ed185aa7.png)

2. Run claim action for vivvestin in iter 3388. No reward record created for new iteration 3388 either. Only two reward records shown for iter 3384 and 3387. Expecting 4 records-> iter 3383, 3384, 3387, 3388.
![Account - Proton Testnet 03-02-2022 16-22-54](https://user-images.githubusercontent.com/77765830/152276189-7c40b0ea-3163-4451-853a-0cf3bc25da39.png)

**Comment by tommccann777** [comment]
I don't know if this helps but the reward record for an iteration is created retrospectively. For example, if it is iteration 100, there will be no reward record for 100. When it becomes iteration 101, new activity (a user doing a survey, vote, ratify or claim) will trigger the new iteration and a reward record is created then for 100.

**Comment by tommccann777** [comment]
Also, I fixed the issue earlier by deleting all of the rewards records. You should see them building up as the iterations progress. At most there should be 4 reward records for the previous 4 iterations in which there was activity.

**Comment by judytan21** [comment]
11/5/22 This is a very old issue and is no longer relevant. Working fine in v0.9.10.
