### ISSUE TITLE
Unable to claim in iteration 5380.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#15]
27/4/22  freeosgov2, ver 0.9.10, account: verovera, current iter: 5380
verovera completed survey, vote and ratify activities in iter 5379.
At 3:02pm, start of iter 5380, ran claim for verovera. Claim action failed with the following error message
![Account - Proton Testnet 27-04-2022 15-03-34](https://user-images.githubusercontent.com/77765830/165432663-8b95d012-cdd0-458e-9a2d-b3dc711904e7.png)
.

**Comment by tommccann777** [comment]
This was due to the contract account not having the eosio.code permission which allows the contract to call inline actions. This has been corrected on the freeosgov2 account. The solution did not require any change to contract code.

Ready for re-testing.

**Comment by judytan21** [comment]
2/5/22 Retested in v0.9.10, Iteration 5501, verovera. Claim successful. Not getting error, Fixed. Close.
