### ISSUE TITLE
Claim payments to users did not match participant_issuance amount.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#19]
25/5/22 freeosgov2 v0.9.17
vivvestin, verovera and vickvindaloo all completed SVR activities in iter 459289 and claimed in the next iteration 459290.
Reward record for iteration 459289 shows iteration_issuance=1101.0855 POINT. Participant_Issuance=367.0285 POINT. Participants=3 
Exchangerate table-> CP=0.01000000000000000  TP=0.01670000000000000
As all of them completed SVR, expecting each one of them to be allocated 100% of the participant_issuance of 367.0285 
with Unlocked=220 POINT and Locked=147 POINT
Checking the freeosgov2 transactions: each one of them only received 54.9444 POINT (unlocked) Lockedaccounts=36.8126 POINT. Total of 91.757 POINT
May 25, 2022 01:02:10 PM        
freeosgov2 - allocate
from: freeosgov2
to: vickvindaloo
quantity: 54.9444 POINT 
memo: Claim for week 459289: Survey [20%]: (18.3514 POINT), Vote [50%]: (45.8785 POINT), Ratify [30%]: (27.5271 POINT)
May 25, 2022 01:01:30 PM        
freeosgov2 - allocate
from: freeosgov2
to: verovera
quantity: 54.9444 POINT
memo: Claim for week 459289: Survey [20%]: (18.3514 POINT), Vote [50%]: (45.8785 POINT), Ratify [30%]: (27.5271 POINT)
May 25, 2022 01:01:10 PM        
freeosgov2 - allocate
from: freeosgov2
to: vivvestin
quantity: 54.9444 POINT
memo: Claim for week 459289: Survey [20%]: (18.3514 POINT), Vote [50%]: (45.8785 POINT), Ratify [30%]: (27.5271 POINT)
![Account - Proton Testnet 25-05-2022 14-33-36](https://user-images.githubusercontent.com/77765830/170170844-f3f8a412-4a54-475b-b90d-23c7bb8dd8ea.png)

**Comment by tommccann777** [comment]
Are you taking the issuance_rate into consideration? It is "issuance_rate": "0.25000000000000000" for iteration 459289. The issuance rate is multiplied against the participant issuance. That makes the figures roughly correct although I haven't calculated exactly.

**Comment by judytan21** [comment]
25/5/22 Multiplying the participant_issuance by the issuance_rate->= 367.0285 * 0.25 = 91.75715. Correct. 
Tom | freeos.io | freedao.io — Today at 16:07
My fault Jude, I sneaked the issuance rate multiplier into the last release. I didn't announce that in the release notes. I'll update them now.

**Comment by judytan21** [comment]
25/5/22 Reopening issue as the participan_issuance already has the issuance_rate applied to it.
Tom | freeos.io | freedao.io — 25/5/22 Today at 17:07
You ain't gonna believe this Jude. I've just reviewed the code for the reward record and participant_issuance ALREADY has the issuance_rate applied to it. I'm going to have to take the 'multiplied by issuance_rate' out of claim again.
I'll get a new version ready for you for next week.

**Comment by judytan21** [comment]
31/5/22 Retest scenario in freeosgov2 Ver 0.9.18. Fixed.
