### ISSUE TITLE
Mintfreeos action failed with assertion failure: the correct mint fee has not been paid.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#23]
21/6/22 freeosgov2 v0.9.22, Iteration = 459939
Mint POINTs to FREEOS using mint fee payment only (no freepoints). freeosgov2 parameter dummyfee=1
User: verovera, mint amount=1.0000 POINT, mintfeefree=None
mintfreeos action failed-> Error assertion failure with message: the correct mint fee has not been paid.
Please note: Got the same error with another test scenario when trying to mint freeos using freepoints/mint fee combo (vivvestin).
![Account - Proton Testnet 21-06-2022 14-25-06](https://user-images.githubusercontent.com/77765830/174703929-28bfe3bb-b805-4a5e-884f-96835bdee301.png)
![Account - Proton Testnet 21-06-2022 14-35-10](https://user-images.githubusercontent.com/77765830/174704277-82a33fc4-6d8a-4a82-ae65-e39244aacf4a.png)

**Comment by tommccann777** [comment]
I think this is the desired behaviour. Did they pay the mint fee of 1 XPR?

**Comment by judytan21** [comment]
29/6/22 Retest. freeosgov2 v0.9.26. Fixed.
