### ISSUE TITLE
When minting freeos using freepoints/mint fee combo, the Credit balance was not reduced after paying mint fee.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#26]
28/6/22 freeosgov2 v0.9.25  iteration: 460108, account=billbeaumont
Mint POINTs to FREEOS using combo of mintfeefree allowance + mint fee. 
Convert 3 POINTs to FREEOS where mintfeefree allowance is < mintfreeos amount i.e. 2.0000 POINT. 
Pay mintfee of 1 XPR for the remaining amount of 1 POINT.
After minting:
-freeos, freeostokens balance increased from 10 to 13 freeos. Correct.
-freeosgov2 bal reduced by 3 POINTs from 100 to 97 POINT. Correct.
-freeosgov2 mintfeefree (freepoints) reduced from 2 POINT to None. Correct.
-freeosgov2 CREDIT balance remain as 1 XPR. Incorrect. Expecting None as CREDIT should have been used as mint fee.
![Account - Proton Testnet 28-06-2022 15-01-16](https://user-images.githubusercontent.com/77765830/176083901-a459f1b5-d644-4963-9195-6fd66e460ff4.png)

**Comment by tommccann777** [comment]
Fixed in 0.9.29 - Ready for restesting

**Comment by judytan21** [comment]
29/6/22 Retest issue. freeosgov2 v0.9.26 account=billbeaumont. Fixed.
After minting:
-freeos, freeostokens balance increased from 13 to 16 freeos. Correct.
-freeosgov2 bal reduced by 3 POINTs from 97 to 94 POINT. Correct.
-freeosgov2 mintfeefree (freepoints) reduced from 2 POINT to None. Correct.
-freeosgov2 CREDIT balance=None as credit used to pay mint fee. Correct.
