### ISSUE TITLE
Assertion failure error when minting FREEBI to FREEOS

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#27]
22/6/22 freegov2 v0.9.25 iteration: 460109, account: vivvestin.
1. Login as vivvestin.
2. Run mintfreeos action-> user: vivvestin, input_quantity: 1.0000 FREEBI, mint_fee_currency: 4,XPR 
3. Submit. Error: assertion failure with message: invalid currency for quantity
![freeosgov2 - XPR Account - Proton Testnet 28-06-2022 16-45-17](https://user-images.githubusercontent.com/77765830/176095618-36b41466-c968-4d35-9919-3d483fc9d236.png)

**Comment by judytan21** [comment]
29/6/22 Retest scenario. - freeosgov2 v0.9.26 vivvestin, still getting the same assertion failure, Not fixed
![freeosgov2 - XPR Account - Proton Testnet 29-06-2022 10-20-49](https://user-images.githubusercontent.com/77765830/176313426-c02de199-9e60-4409-9d72-19b65a15f964.png)
,

**Comment by judytan21** [comment]
4/7/22 Retest. freeosgov2 v0.9.27, account: vivvestin. Failed with assertion failure with message: read.
![Account - Proton Testnet 04-07-2022 10-51-44](https://user-images.githubusercontent.com/77765830/177059845-d08fba46-c4c9-48b2-9942-2e19987f3032.png)

**Comment by judytan21** [comment]
6/7/22 Retest. freeosgov2 v0.9.28 iteration: 460295, account=vivvestin. Not fixed.
Mint FREEBI to FREEOS usingmintfeefree allowance only
Transferred 1.0000 FREEBI to freeosgov2 as a CREDIT before running mintfreeos action, 
After minting:
-freeos, freeostokens balance increased from 10 to 11 freeos. Correct.
-freeosgov2 bal remain the same at 1800.3716 POINT. Correct.
-freeosgov2 mintfeefree (freepoints) reduced from 89 POINT to 88 POINT. Expecting to remain as 89 POINT.
-freeosgov2 CREDIT balance remain as 1.0000FREEBI. Expecting None as CREDIT should have been used as mint fee.

**Comment by tommccann777** [comment]
I'm not sure why you are paying 1 XPR as the mint fee. vivvestin has mintfeefree = 88/89 points. The mint fee should not be necessary

**Comment by judytan21** [comment]
7/7/22 Ooops! copy n paste botch up. I did not pay mintfee of 1 XPR but transferred 1.0000 FREEBI to freeosgov2 as a CREDIT before running mintfreeos action, Have updated desc accordingly.

**Comment by judytan21** [comment]
11/7/22 Retest. freeosgov2 v0.9.29 iteration 460419. Fixed.
