### ISSUE TITLE
Assertion failure encountered when minting freeos using mintfeefree allowance only.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#28]
29/6/22 freeosgov2 v0.9.26 iter=460129 account billbeaumont.
When minting freeos using freepoints only (mintfeefree=10.0000 POINT), mint amount=10.0000 POINT, No mint fee required.
Encountered Error:assertion failure with message: cannot pass end iterator to erase

![freeosgov2 - XPR Account - Proton Testnet 29-06-2022 12-16-46](https://user-images.githubusercontent.com/77765830/176325167-637472f1-c27c-4ac8-bfab-919485d12a61.png)

**Comment by tommccann777** [comment]
I have fixed this in v0.9.27. Ready for re-test

**Comment by judytan21** [comment]
6/7/22 Retest. freeosgov2 v0.9.28 account billbeaumont. Fixed.
