### ISSUE TITLE
Vote completion was incorrectly recorded in vote4 field in svrs table

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#5]
14/12/21 Contract: freeosgov, account: billbeaumont, Version# v0.7.5, Bloks.io
Vote completed for billbeaumont in iteration 2163. Checked the svrs table. Iteration 2163 was recorded in survey4 field. Expecting the iteration# to be stored in the vote3 field which was 0.
Steps:
1. Did not participate in Survey for billbeaumont in iteration 2163.
2. Submit vote completion for billbeaumont at 03:32PM within the Vote start/end times.
3. Vote successful.
4. Check svrs table. Scope: billbeaumont

![Account - Proton Testnet 14-12-2021 15-39-31](https://user-images.githubusercontent.com/77765830/145924141-4665760b-c7c9-4147-b5c9-ce41e62d1c55.png)

**Comment by tommccann777** [comment]
I don't understand the report. If bill votes in iteration 2163 then the modulus 4 of 2163 = 3 which means that the iteration is recorded in the vote4 field, and it is.

**Comment by judytan21** [comment]
11/5/22 This is a very old issue and no longer relevant. v0.9.10 Governance dApp is now using modulus 5 instead of Mod 4 technique for storing activities in SVRS table. Working fine.
