### ISSUE TITLE
Suggestion: Reword error message displayed.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#6]
15/12/21 Contract: freeosgov, account: billbeaumont, Version# v0.7.5, Bloks.io
Entered a -ve value for vote q1response. Error displayed-Encoding error at root<vote>.q1response<uint8>: Number -1 underflows uint8. 
Would it be possible to use the same  out of range message i.e. Response 1 is out of range. More user friendly without the technical jargon.

**Comment by tommccann777** [comment]
That error message is generated by Proton. It is expecting a positive integer (uint8 = unsigned integer 8 bits) but it was supplied with a negative number. The error is intercepted by Proton before it is delivered to the smart contract code.

**Comment by judytan21** [comment]
15/12/21 - See Tom's comment that it's not possible to reword error message.
