### ISSUE TITLE
Out of range value for Survey q2response was accepted.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#7]
15/12/21 Contract: freeosgov, account: billbeaumont, Version# v0.7.5, Bloks.io
When completing survey, entered a value of 25 for q2response and an out of range value of 0 for q3response. 
On submission, got error: assertion failure with message: Response 3 must be a number between 1 and 3.
Expecting q2response of 25 to be rejected as valid value must be from 1-24 months. Instead it accepted q2response and rejected q3response. 

![Account - Proton Testnet 15-12-2021 11-23-23](https://user-images.githubusercontent.com/77765830/146089086-46b95454-6548-4708-85af-443d4ae80ce6.png)

**Comment by tommccann777** [comment]
This looks like it is behaving as expected. The surveyranges parameter has the value:

{
      "paramname": "surveyranges",
      "value": "q1.2:1-48,q2.2:1-48"
}

**Comment by judytan21** [comment]
15/12/21 Contract: freeosgov, account: billbeaumont, Version# v0.7.6, B Iterations 2186, Bloks.io
Retest after Tom has updated the parameters table, surveyranges to q1.2:1-24,q2.2:1-24 (valid values for q2 1-24months).
Value 25 rejected. Error: assertion failure with message: Response 2 is out of range
Fixed. Issue#7 closed.
