### ISSUE TITLE
Mint Freeby- Loading pop up box displayed when entering an invalid amount.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov#8]
25/01/22 Contract: freeosgov, account: verovera, Version# verov0.8.5, iter 3169 Bloks.io
1. Ran 'Mint Freeby' action with authority of verovera.
2. Enter 0 amount without the SYMBOL or a non numeric value.
3. "Loading ... preparing request" pop up box displayed with "Error-Encoding error at root<mintfreeby>.quantity<asset>: Symbol is required when creating Asset" from number in the background. Screenshot attached.

![Account - Proton Testnet 25-01-2022 13-45-59](https://user-images.githubusercontent.com/77765830/150890565-69e40e09-6bd4-4a6d-85e3-a50ab2ae0ca7.png)

**Comment by tommccann777** [comment]
The assert error message is issued by the Proton blockchain, one of many related messages when an invalid parameter is supplied. It is not an issue for the application itself.

**Comment by judytan21** [comment]
26/1/22 Close issue as per Tom's comments above.
